name: Tests de l'API

on:
  push:
    branches: [main]

jobs:
  unit-test:
    name: Run API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "22"
      - run: cd backend && npm install
      - run: cd backend && npm test_api
      - run: cp ./backend/tests/.env.test ./backend/.env